// JAI Excel/src/taskpane/app/app.component.ts
import { Component } from "@angular/core";
import { authenticate, getEnvironments, getDatabaseInfo, setEnvironment } from "jai-sdk";

@Component({
  selector: "app-home",
  templateUrl: "./app.component.html",
})
export default class AppComponent {
  apiKey: string = "";

  isAuthenticated: boolean = false;

  environments = [];

  async login() {
    try {
      if (!this.apiKey) {
        return;
      }
      authenticate(this.apiKey);

      this.environments = await getEnvironments();
      setEnvironment(null);
      this.isAuthenticated = true;

      console.log(await getDatabaseInfo("complete"));
      console.log(await getDatabaseInfo("names"));
    } catch (error) {
      console.error(error);
    }
  }
}

<header class="ms-welcome__header ms-bgColor-neutralLighter ms-u-fadeIn500">
  <img
    width="90"
    height="60"
    src="../../../assets/logo-filled.png"
    alt="Contoso Task Pane Add-in"
    title="Contoso Task Pane Add-in"
  />
  <h1 class="ms-fontSize-su ms-fontWeight-light ms-fontColor-neutralPrimary">Welcome</h1>
</header>
<main class="ms-welcome__main">
  <h3 class="ms-font-xl ms-fontWeight-semilight ms-fontColor-neutralPrimary ms-u-slideUpIn20">
    Insert your key
  </h3>

  <input required style="min-width: 95%" [(ngModel)]="apiKey" />
  <br />
  <h3 *ngIf="isAuthenticated" class="ms-font-xl ms-fontWeight-semilight ms-fontColor-neutralPrimary ms-u-slideUpIn20">
    Select an environment
  </h3>
  <select *ngIf="isAuthenticated" style="min-width: 60%">
    <option *ngFor="let env of environments" [value]="env.id">
      {{ env.name }}
    </option>
  </select>
  <div role="button" class="ms-welcome__action ms-Button ms-Button--hero ms-u-slideUpIn20" (click)="login()">
    <button class="ms-Button-label">Access</button>
  </div>
</main>

// react-addin-project/src/taskpane/components/App.tsx
import * as React from "react";
import Header from "./Header";
import Progress from "./Progress";
import { authenticate, getDatabaseInfo, getEnvironments, setEnvironment } from "jai-sdk";
import "@coreui/coreui/dist/css/coreui.min.css";
import { ApiKeyForm } from "./ApiKeyForm";
import { Link } from "react-router-dom";

export interface AppProps {
  title: string;
  isOfficeInitialized: boolean;
}

export default class App extends React.Component<AppProps> {
  apiKey: string;
  isAuthenticated: boolean = false;
  environments = [];

  constructor(props, context) {
    super(props, context);
    this.state = {
      listItems: [],
    };
  }

  componentDidMount() {}

  authenticate = async () => {
    try {
      console.log(this.apiKey);
      if (!this.apiKey) {
        return;
      }
      authenticate(this.apiKey);

      this.environments = await getEnvironments();
      console.log(this.environments);

      setEnvironment(null);

      this.isAuthenticated = true;

      console.log(await getDatabaseInfo("complete"));

      console.log(await getDatabaseInfo("names"));
    } catch (error) {
      console.error(error);
    }
  };

  render() {
    const { title, isOfficeInitialized } = this.props;

    if (!isOfficeInitialized) {
      return (
        <Progress
          title={title}
          logo={require("./../../../assets/logo-filled.png")}
          message="Please sideload your addin to see app body."
        />
      );
    }

    return (
      <div className="ms-welcome">
        <Header logo={require("./../../../assets/logo-filled.png")} title={this.props.title} message="Welcome" />
        <Link to="/Herolist">Expenses</Link>
        <ApiKeyForm></ApiKeyForm>
      </div>
    );
  }
}
